/**********************************************************************\

PROGRAM:       C:\MEPS\PROG\EXAMPLE10.SAS

DESCRIPTION:  	THIS EXAMPLE COMPARES HOSPITAL INPATIENT EXPENDITURES
               (FACILITY, PHYSICIAN, TOTAL) FOR STAYS THAT DO AND DO
               NOT INCLUDE FACILITY EXPENDITURES FOR THE PRECEDING 
               EMERGENCY ROOM VISIT.
		         
		         RECORDS WITH PRECEDING ER FACILITY EXPENDITURES ARE
		         IDENTIFIED BY THE VARIABLE ERHEVIDX.

INPUT FILE:  	C:\MEPS\DATA\H77F.SAS7BDAT (2003 HOSP. INPATIENT FILE)

\**********************************************************************/

FOOTNOTE 'PROGRAM: C:\MEPS\PROG\PMED\EXAMPLE10.SAS';

LIBNAME CDATA 'C:\MEPS\DATA';
LIBNAME PUF67 'T:\AHRQPUF\HCPUFS\HC067D\DATA';

TITLE1 'AHRQ MEPS DATA USERS WORKSHOP -- JULY 2006';
TITLE2 'HOSPITAL INPATIENT STAY EXPENDITURES:';
TITLE3 'COMPARING STAYS WITH AND WITHOUT PRECEDING ER FACILITY EXPENDITURES';

PROC FORMAT;
   VALUE EREXPF
   0 = 'ER_YES'
   1 = 'ER__NO';
RUN;

DATA STAZ2002;
   SET PUF67.H67DV1X (KEEP= DUPERSID ERHEVIDX IPXP02X IPFXP02X IPDXP02X
                         PERWT02F VARSTR VARPSU);

DATA STAZ2003;
   SET CDATA.H77D (KEEP= DUPERSID ERHEVIDX IPXP03X IPFXP03X IPDXP03X
                         PERWT03F VARSTR VARPSU);
   IF ERHEVIDX NE -1
      THEN ER_FACEX = 0;
   ELSE ER_FACEX = 1;
   LABEL ER_FACEX = '=0 IF INCLUDES ER FACILITY EXP';
RUN;

TITLE4 'TOTAL 2002 IP EXPENDITURES (IPXP02X)';

PROC SURVEYMEANS DATA= STAZ2002 NOBS SUMWGT MEAN STDERR ;
   STRATA VARSTR;
   CLUSTER VARPSU;
   WEIGHT PERWT02F;
   VAR IPXP02X ;
RUN;

TITLE4 'TOTAL 2003 IP EXPENDITURES (IPXP03X)';

PROC SURVEYMEANS DATA= STAZ2003 NOBS SUMWGT MEAN STDERR ;
   STRATA VARSTR;
   CLUSTER VARPSU;
   WEIGHT PERWT03F;
   VAR IPXP03X ;
   DOMAIN ER_FACEX ;
RUN;

PROC SURVEYREG DATA= STAZ2003;
   STRATA VARSTR;
   CLUSTER VARPSU;
   WEIGHT PERWT03F;
   MODEL IPXP03X = ER_FACEX ;
RUN;

TITLE4 'FACILITY IP EXPENDITURES (IPFXP03X)';

PROC SURVEYMEANS DATA= STAZ2003 NOBS SUMWGT MEAN STDERR ;
   STRATA VARSTR;
   CLUSTER VARPSU;
   WEIGHT PERWT03F;
   VAR IPFXP03X ;
   DOMAIN ER_FACEX ;
RUN;

PROC SURVEYREG DATA= STAZ2003;
   STRATA VARSTR;
   CLUSTER VARPSU;
   WEIGHT PERWT03F;
   MODEL IPFXP03X = ER_FACEX ;
RUN;

TITLE4 'PHYSICIAN IP EXPENDITURES (IPDXP03X)';

PROC SURVEYMEANS DATA= STAZ2003 NOBS SUMWGT MEAN STDERR ;
   STRATA VARSTR;
   CLUSTER VARPSU;
   WEIGHT PERWT03F;
   VAR IPDXP03X ;
   DOMAIN ER_FACEX ;
RUN;

PROC SURVEYREG DATA= STAZ2003;
   STRATA VARSTR;
   CLUSTER VARPSU;
   WEIGHT PERWT03F;
   MODEL IPDXP03X = ER_FACEX ;
RUN;